name: Build ESP-BOX S3-BOX-3

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout esp-box
        uses: actions/checkout@v4
        with:
          repository: espressif/esp-box
          submodules: recursive

      - name: Build factory_demo
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.3
          target: esp32s3
          path: examples/factory_demo
          command: |
            rm -f sdkconfig sdkconfig.defaults
            cp sdkconfig.ci.box sdkconfig.defaults
            echo "CONFIG_ESP_BOX_BOARD_S3_BOX_3=y" >> sdkconfig.defaults
            echo "CONFIG_BSP_TOUCH_ENABLED=y" >> sdkconfig.defaults

            idf.py set-target esp32s3
            idf.py build

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: esp-box-s3-build
          path: |
            examples/factory_demo/build/*.bin
            examples/factory_demo/build/bootloader/*.bin
            examples/factory_demo/build/partition_table/*.bin
