name: Build ESP32-S3-BOX-3

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout esp-box
        uses: actions/checkout@v4
        with:
          repository: espressif/esp-box
          submodules: recursive

      - name: Build + Auto Merge
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.3
          target: esp32s3
          path: examples/factory_demo
          command: |

            set -e

            idf.py fullclean
            idf.py set-target esp32s3

            cp sdkconfig.ci.box sdkconfig.defaults
            echo "CONFIG_ESP_BOX_BOARD_S3_BOX_3=y" >> sdkconfig.defaults
            echo "CONFIG_ESPTOOLPY_FLASHSIZE_16MB=y" >> sdkconfig.defaults

            idf.py build

            echo "===== AUTO MERGE USING IDF ====="
            idf.py merge-bin -o build/firmware_merged.bin

            echo "===== VERIFY MERGED FILE ====="
            ls -lah build/firmware_merged.bin

      - name: Upload merged firmware
        uses: actions/upload-artifact@v4
        with:
          name: esp32s3-box3-merged
          path: examples/factory_demo/build/firmware_merged.bin
